export const regions = [
  "CA - San Diego South",
  "New Hampshire",
  "Massachusetts",
  "Maine",
  "Rhode Island",
].sort();

export const breaks = [
  {
    break_name: "Pacific Beach",
    location: "San Diego",
    region: "CA - San Diego South",
    lat: "32.8025",
    lng: "-117.2357",
  },
  {
    break_name: "The Wall",
    location: "Hampton Beach, New Hampshire",
    region: "New Hampshire",
    lat: "42.9340",
    lng: "-70.7984",
  },
  {
    break_name: "Long Sands Beach",
    location: "York, Maine",
    region: "Maine",
    lat: "43.158845",
    lng: "-70.610971",
  },
  {
    break_name: "Wells Beach",
    location: "Wells, Maine",
    region: "Maine",
    lat: "43.303143",
    lng: "-70.560127",
  },
  {
    break_name: "Ogunquit",
    location: "Ogunquit, Maine",
    region: "Maine",
    lat: "43.255950",
    lng: "-70.589231",
  },
  {
    break_name: "Gooch's Beach",
    location: "Kennebunk, Maine",
    region: "Maine",
    lat: "43.345847",
    lng: "-70.481133",
  },
  {
    break_name: "Higgins Beach",
    location: "Scarborough, Maine",
    region: "Maine",
    lat: "43.560229",
    lng: "-70.275599",
  },
  {
    break_name: "Old Orchard Beach",
    location: "Old Orchard Beach, Maine",
    region: "Maine",
    lat: "43.516102",
    lng: "-70.366669",
  },
  {
    break_name: "Scarborough Beach",
    location: "Scarborough, Maine",
    region: "Maine",
    lat: "43.545352",
    lng: "-70.305681",
  },
  {
    break_name: "Seabrook Beach",
    location: "Seabrook, New Hampshire",
    region: "New Hampshire",
    lat: "42.887337",
    lng: "-70.813027",
  },
  {
    break_name: "Fox Hill",
    location: "North Hampton, New Hampshire",
    region: "New Hampshire",
    lat: "42.963968",
    lng: "-70.769600",
  },
  {
    break_name: "Sawyer's Beach",
    location: "Rye, New Hampshire",
    region: "New Hampshire",
    lat: "42.9789",
    lng: "-70.7644",
  },
  {
    break_name: "Jenness Beach",
    location: "Rye, New Hampshire",
    region: "New Hampshire",
    lat: "42.985750",
    lng: "-70.761851",
  },
  {
    break_name: "Long Beach",
    location: "Gloucester, Massachusetts",
    region: "Massachusetts",
    lat: "42.629691",
    lng: "-70.616453",
  },
  {
    break_name: "Nahant Beach",
    location: "Nahant, Massachusetts",
    region: "Massachusetts",
    lat: "42.443614",
    lng: "-70.936530",
  },
  {
    break_name: "Nantasket Beach",
    location: "Hull, Massachusetts",
    region: "Massachusetts",
    lat: "42.275450",
    lng: "-70.859822",
  },
  {
    break_name: "Cape Cod",
    location: "Cape Cod, Massachusetts",
    region: "Massachusetts",
    lat: "41.932286",
    lng: "-69.976061",
  },
  {
    break_name: "Nauset Beach",
    location: "Cape Cod, Massachusetts",
    region: "Massachusetts",
    lat: "41.788007",
    lng: "-69.935384",
  },
  {
    break_name: "Martha's Vineyard",
    location: "Martha's Vineyard, Massachusetts",
    region: "Massachusetts",
    lat: "41.347121",
    lng: "-70.641002",
  },
  {
    break_name: "Nantucket",
    location: "Nantucket, Massachusetts",
    region: "Massachusetts",
    lat: "41.242832",
    lng: "-70.068488",
  },
  {
    break_name: "Second Beach",
    location: "Middletown, Rhode Island",
    region: "Rhode Island",
    lat: "41.484597",
    lng: "-71.263422",
  },
  {
    break_name: "Ruggles",
    location: "Newport, Rhode Island",
    region: "Rhode Island",
    lat: "41.465333",
    lng: "-71.296848",
  },
  {
    break_name: "Narragansett Town Beach",
    location: "Narragansett, Rhode Island",
    region: "Rhode Island",
    lat: "41.428718",
    lng: "-71.452269",
  },
  {
    break_name: "Point Judith",
    location: "Point Judith, Rhode Island",
    region: "Rhode Island",
    lat: "41.358274",
    lng: "-71.477853",
  },
  // {
  //   break_name: "",
  //   location: ", Rhode Island",
  //   region: "Rhode Island",
  //   lat: "",
  //   lng: "",
  // },
  // {
  //   break_name: "",
  //   location: ", Rhode Island",
  //   region: "Rhode Island",
  //   lat: "",
  //   lng: "",
  // },
];
